### ISSUE TITLE
stuck on loading results

### ISSUE THREAD

**Issue by zany130** [AdamTillou/ULauncherAurman#1]
displays loading indefintly

**Comment by benzanol** [comment]
Sorry for the late reply, I don't actually use arch as my primary system anymore. It seemed that for searches which yielded too many results (1000+) ulauncher would try to display all of them, which would make it larger than the largest possible window, so ulauncher would just hang. I added a section in the latest commit to limit the number of packages to display to 20, so it should work just fine now after you update it. Also note that aurman is now unmaintained, so this plugin now uses yay, so that will have to be installed if it isn't already.
